spring.application.name=consumer

spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=messagesdb
spring.data.mongodb.username=root
spring.data.mongodb.password=secret
spring.data.mongodb.authentication-database=admin

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=secret

server.port=8081